
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]


[shell]
program=zsh

[env]
TERM = "screen-256color"

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "None"
startup_mode = "Fullscreen"

