

[terminal.shell]
program = "zsh"

[env]
TERM = "screen-256color"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Fullscreen"

[general]

import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[terminal]

